add entropy-generator library, connect the drawing data with the entr…
mintlayer/mojito-browser-extension pull request #75
Opened 2023-02-16 15:25 UTC by owlsua

…opy generation

# :speech_balloon: Description 

Describe here the main purpose of your Pull Request. Eg:

Created a new screen to be the second step of the account creation user flow.

### More

**[If needed]** List here other this you've done in this PR. Eg.:

- Refactoring user validation to improve code readability
- Improving account creation tests to verify if the password set is strong enough

# :camera: Screenshots

**[If needed]** List here how the component/screen/behavior should look like in the design and how it is being rendered. You can list different screenshots for states of that component/screen/behavior. Animated GIFs can be used if needed!

# :clipboard: Checklist:

- [ ] I have named my branch as `A-[id of Asana task]`
- [ ] I have set the title of my PR as `A-[id of Asana task]: [short description]`
- [ ] My changes passed successfully by `prettier` check
- [ ] My changes passed successfully by `lint` check
- [ ] My changes kept the previous test coverage rate
- [ ] I have added enough tests for my new feature/bugfix
- [ ] I have set at least one person to review this PR
- [ ] I have set myself as the assignee of this PR
- [ ] I have set at least one label to this PR

2023-03-01 14:31 UTC, renie requested changes
The restoring process progress steps do not look right:
![Screenshot from 2023-03-01 16-23-24](https://user-images.githubusercontent.com/324830/222169652-de8f9598-f573-48fc-9328-a53f06224fec.png)

It should look like on creation screen, where the bars almost touch each other:
![Screenshot from 2023-03-01 16-23-31](https://user-images.githubusercontent.com/324830/222169984-4952a3f5-8b58-43f5-94b3-b362929bf3c4.png)

2023-03-01 14:31 UTC, renie commented on src/utils/Helpers/Array/Array.js
> +const getNRandomElementsFromArray = (array, n) => {
Can we please have a test for this?

2023-03-02 10:08 UTC, owlsua commented on src/utils/Helpers/Array/Array.js
> +const getNRandomElementsFromArray = (array, n) => {
Done

2023-03-14 10:05 UTC, renie approved these changes

2023-03-14 10:06 UTC, renie commented
Sound good to me. Just change the target branch to `dev` before merging, then merge it, and close PR #73 with a comment pointing to this branch, please.

2023-03-14 10:25 UTC, merged